spring:
  profiles: # 配置当前环境
    active: dev
  datasource: #数据库
    url: jdbc:mysql://8.129.218.89:3306/db_test
    username: ActSpirits
    password: Scwm,dnyx0
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:  #rest
    hiddenmethod:
      filter:
        enabled: true
  mail: #mail
    port: 465
    host: smtp.qq.com
    username: 1697279908@qq.com
    password: angvthuisqpjchdb
    default-encoding: utf-8
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
            socketFactory:
              port: 465
              class: javax.net.ssl.SSLSocketFactory
  redis: #redis
    host: 8.129.218.89
    port: 6380
    password: Scwm,dnyx0
    database: 0
    connect-timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
server:
  port: 8080

